name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
